from tkinter import *
a=Tk()
a.title("my first window ")
a.geometry("1920x1080+500+500")
m1=Menu()
l1=Menu()
l1.add_command(lable="newfile")
l1.add_command(lable="openfile")
l1.add_command(lable="savefile")
l2=Menu()
l2.add_command(lable="copy")
l2.add_command(lable="past")
l2.add_command(lable="undo")
m1.add_casscade(lable="file",menu=l1)
m1.add_casscade(lable="edit")
m1.add_casscade(lable="format")
m1.add_casscade(lable="view")
m1.add_casscade(lable="help")
a.config(menu=m1)
a.mainloop()
